const assert = require("assert");
const { parseConfig } = require("../src/config");
const { generateTs, buildTree } = require("../src/codegen");
const { EXT_TO_ASSET_TYPE } = require("../src/sync");

// --- Config parsing ---
console.log("Testing config parsing...");

const toml = `
[creator]
type = "user"
id = 12345

[[sync]]
name = "images"
path = "assets/images"
output = "src/shared/image-assets.ts"

[[sync]]
name = "meshes"
path = "assets/meshes"
output = "src/shared/mesh-assets.ts"
assetType = "Model"
`;

const config = parseConfig(toml);
assert.deepStrictEqual(config.creator, { type: "user", id: 12345 });
assert.strictEqual(config.sync.length, 2);
assert.strictEqual(config.sync[0].name, "images");
assert.strictEqual(config.sync[0].path, "assets/images");
assert.strictEqual(config.sync[1].assetType, "Model");
console.log("  config parsing OK");

// --- Config with comments ---
console.log("Testing config with comments...");

const toml2 = `
[creator]
type = "group"
id = 99999 # my group

[[sync]]
name = "sounds"
path = "assets/sounds"
output = "src/shared/sound-assets.ts"
`;

const config2 = parseConfig(toml2);
assert.strictEqual(config2.creator.type, "group");
assert.strictEqual(config2.creator.id, 99999);
console.log("  config with comments OK");

// --- Tree building ---
console.log("Testing tree building...");

const lock = {
	"ui/button": { assetId: "111" },
	"ui/icon": { assetId: "222" },
	"fx/spark": { assetId: "333" },
	"logo": { assetId: "444" },
};

const tree = buildTree(lock);
assert.strictEqual(tree.ui.button, "rbxassetid://111");
assert.strictEqual(tree.ui.icon, "rbxassetid://222");
assert.strictEqual(tree.fx.spark, "rbxassetid://333");
assert.strictEqual(tree.logo, "rbxassetid://444");
console.log("  tree building OK");

// --- TypeScript generation ---
console.log("Testing TypeScript generation...");

const ts = generateTs(lock, "imageAssets");
assert(ts.includes("const imageAssets ="));
assert(ts.includes("as const"));
assert(ts.includes("export = imageAssets"));
assert(ts.includes('"rbxassetid://111"'));
assert(ts.includes("auto-generated by rocs"));
console.log("  TypeScript generation OK");

// --- Flat keys ---
console.log("Testing flat keys (no nesting)...");

const flatLock = {
	"myMesh": { assetId: "555" },
	"otherMesh": { assetId: "666" },
};

const flatTs = generateTs(flatLock, "meshAssets");
assert(flatTs.includes('myMesh: "rbxassetid://555"'));
assert(flatTs.includes('otherMesh: "rbxassetid://666"'));
console.log("  flat keys OK");

// --- Extension mapping ---
console.log("Testing extension mapping...");

assert.strictEqual(EXT_TO_ASSET_TYPE[".png"], "Decal");
assert.strictEqual(EXT_TO_ASSET_TYPE[".wav"], "Audio");
assert.strictEqual(EXT_TO_ASSET_TYPE[".flac"], "Audio");
assert.strictEqual(EXT_TO_ASSET_TYPE[".fbx"], "Model");
assert.strictEqual(EXT_TO_ASSET_TYPE[".rbxm"], "Animation");
assert.strictEqual(EXT_TO_ASSET_TYPE[".mp4"], "Video");
assert.strictEqual(EXT_TO_ASSET_TYPE[".mov"], "Video");
assert.strictEqual(EXT_TO_ASSET_TYPE[".xyz"], undefined);
console.log("  extension mapping OK");

console.log("\nAll tests passed!");
