const assert = require("assert");
const { parseConfig } = require("../src/config");
const { generateLuau, generateDts, buildTree, renderLuauType } = require("../src/codegen");
const { EXT_TO_ASSET_TYPE } = require("../src/sync");

// --- Config parsing ---
console.log("Testing config parsing...");

const toml = `
[creator]
type = "user"
id = 12345

[[sync]]
name = "images"
path = "assets/images"
output = "src/shared/image-assets.ts"

[[sync]]
name = "meshes"
path = "assets/meshes"
output = "src/shared/mesh-assets.ts"
assetType = "Model"
`;

const config = parseConfig(toml);
assert.deepStrictEqual(config.creator, { type: "user", id: 12345 });
assert.strictEqual(config.sync.length, 2);
assert.strictEqual(config.sync[0].name, "images");
assert.strictEqual(config.sync[0].path, "assets/images");
assert.strictEqual(config.sync[1].assetType, "Model");
console.log("  config parsing OK");

// --- Config with comments ---
console.log("Testing config with comments...");

const toml2 = `
[creator]
type = "group"
id = 99999 # my group

[[sync]]
name = "sounds"
path = "assets/sounds"
output = "src/shared/sound-assets.ts"
`;

const config2 = parseConfig(toml2);
assert.strictEqual(config2.creator.type, "group");
assert.strictEqual(config2.creator.id, 99999);
console.log("  config with comments OK");

// --- Tree building (with extensions in keys) ---
console.log("Testing tree building...");

const lock = {
	"ui/button.png": { assetId: "111" },
	"ui/icon.png": { assetId: "222" },
	"fx/spark.png": { assetId: "333" },
	"logo.png": { assetId: "444" },
};

const tree = buildTree(lock);
assert.strictEqual(tree.ui["button.png"], "rbxassetid://111");
assert.strictEqual(tree.ui["icon.png"], "rbxassetid://222");
assert.strictEqual(tree.fx["spark.png"], "rbxassetid://333");
assert.strictEqual(tree["logo.png"], "rbxassetid://444");
console.log("  tree building OK");

// --- Luau generation ---
console.log("Testing Luau generation...");

const luau = generateLuau(lock, "images");
assert(luau.includes("local images ="));
assert(luau.includes("return images"));
assert(luau.includes('["button.png"] = "rbxassetid://111"'));
assert(luau.includes('["spark.png"] = "rbxassetid://333"'));
assert(luau.includes("auto-generated by rocs"));
console.log("  Luau generation OK");

// --- d.ts generation ---
console.log("Testing d.ts generation...");

const dts = generateDts(lock, "images");
assert(dts.includes("declare const images:"));
assert(dts.includes("export = images"));
assert(dts.includes('"button.png": string'));
assert(dts.includes('"icon.png": string'));
assert(dts.includes("auto-generated by rocs"));
console.log("  d.ts generation OK");

// --- Flat keys ---
console.log("Testing flat keys (no nesting)...");

const flatLock = {
	"walk.rbxm": { assetId: "555" },
	"run.rbxm": { assetId: "666" },
};

const flatLuau = generateLuau(flatLock, "animations");
assert(flatLuau.includes('["walk.rbxm"] = "rbxassetid://555"'));
assert(flatLuau.includes('["run.rbxm"] = "rbxassetid://666"'));

const flatDts = generateDts(flatLock, "animations");
assert(flatDts.includes('"walk.rbxm": string'));
assert(flatDts.includes('"run.rbxm": string'));
console.log("  flat keys OK");

// --- stripExtensions ---
console.log("Testing stripExtensions...");

const treeStripped = buildTree(lock, { stripExtensions: true });
assert.strictEqual(treeStripped.ui.button, "rbxassetid://111");
assert.strictEqual(treeStripped.ui.icon, "rbxassetid://222");
assert.strictEqual(treeStripped.fx.spark, "rbxassetid://333");
assert.strictEqual(treeStripped.logo, "rbxassetid://444");
console.log("  stripExtensions OK");

// --- Luau strict mode generation ---
console.log("Testing Luau strict mode generation...");

const luauStrict = generateLuau(lock, "images", { strict: true, stripExtensions: true });
assert(luauStrict.includes("--!strict"));
assert(luauStrict.includes("type ImagesType = {"));
assert(luauStrict.includes("local images: ImagesType = {"));
assert(luauStrict.includes("return images"));
assert(luauStrict.includes("\tbutton: string,"));
assert(luauStrict.includes('\tbutton = "rbxassetid://111"'));
assert(!luauStrict.includes(".png"));
console.log("  Luau strict mode OK");

// --- Luau generation with stripExtensions (non-strict) ---
console.log("Testing Luau generation with stripExtensions...");

const luauStripOnly = generateLuau(lock, "images", { stripExtensions: true });
assert(!luauStripOnly.includes("--!strict"));
assert(luauStripOnly.includes('button = "rbxassetid://111"'));
assert(!luauStripOnly.includes(".png"));
console.log("  Luau stripExtensions (non-strict) OK");

// --- d.ts generation with stripExtensions ---
console.log("Testing d.ts generation with stripExtensions...");

const dtsStripped = generateDts(lock, "images", { stripExtensions: true });
assert(dtsStripped.includes("button: string"));
assert(dtsStripped.includes("spark: string"));
assert(!dtsStripped.includes(".png"));
console.log("  d.ts stripExtensions OK");

// --- Config with format and stripExtensions ---
console.log("Testing config with format and stripExtensions...");

const toml3 = `
[creator]
type = "user"
id = 12345

[[sync]]
name = "images"
path = "assets/images"
output = "src/shared/images"
format = "luau"
stripExtensions = true
`;

const config3 = parseConfig(toml3);
assert.strictEqual(config3.sync[0].format, "luau");
assert.strictEqual(config3.sync[0].stripExtensions, true);
console.log("  config format/stripExtensions OK");

// --- Extension mapping ---
console.log("Testing extension mapping...");

assert.strictEqual(EXT_TO_ASSET_TYPE[".png"], "Decal");
assert.strictEqual(EXT_TO_ASSET_TYPE[".wav"], "Audio");
assert.strictEqual(EXT_TO_ASSET_TYPE[".flac"], "Audio");
assert.strictEqual(EXT_TO_ASSET_TYPE[".fbx"], "Model");
assert.strictEqual(EXT_TO_ASSET_TYPE[".rbxm"], "Animation");
assert.strictEqual(EXT_TO_ASSET_TYPE[".mp4"], "Video");
assert.strictEqual(EXT_TO_ASSET_TYPE[".mov"], "Video");
assert.strictEqual(EXT_TO_ASSET_TYPE[".xyz"], undefined);
console.log("  extension mapping OK");

console.log("\nAll tests passed!");
