/**
 * lock オブジェクトからネスト構造の TypeScript コードを生成
 *
 * lock のキーはスラッシュ区切りの相対パス (e.g. "ui/icons/star")
 * → ネストされたオブジェクトに変換
 *
 * @param {Record<string, { assetId: string }>} lock
 * @param {string} varName - エクスポートする変数名
 * @returns {string}
 */
function generateTs(lock, varName) {
	const tree = buildTree(lock);
	const body = renderObject(tree, 1);
	return (
		`// This file is auto-generated by rocs. Do not edit manually.\n` +
		`const ${varName} = ${body} as const;\n` +
		`export = ${varName};\n`
	);
}

/**
 * フラットなキーからネスト構造を構築
 * "a/b/c" → { a: { b: { c: "rbxassetid://..." } } }
 */
function buildTree(lock) {
	const tree = {};
	const keys = Object.keys(lock).sort();
	for (const key of keys) {
		const parts = key.split("/");
		let node = tree;
		for (let i = 0; i < parts.length - 1; i++) {
			if (!node[parts[i]] || typeof node[parts[i]] === "string") {
				node[parts[i]] = {};
			}
			node = node[parts[i]];
		}
		node[parts[parts.length - 1]] = `rbxassetid://${lock[key].assetId}`;
	}
	return tree;
}

/**
 * オブジェクトを TypeScript リテラルとしてレンダリング
 */
function renderObject(obj, depth) {
	const indent = "\t".repeat(depth);
	const closingIndent = "\t".repeat(depth - 1);
	const entries = Object.entries(obj);

	if (entries.length === 0) return "{}";

	const lines = entries.map(([key, value]) => {
		const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `"${key}"`;
		if (typeof value === "string") {
			return `${indent}${safeKey}: "${value}",`;
		}
		return `${indent}${safeKey}: ${renderObject(value, depth + 1)},`;
	});

	return `{\n${lines.join("\n")}\n${closingIndent}}`;
}

module.exports = { generateTs, buildTree, renderObject };
