/**
 * lock オブジェクトから .luau + .d.ts ペアを生成
 * Asphalt と同じ形式: .luau に実際の値、.d.ts に型定義
 *
 * lock のキーはスラッシュ区切りの相対パス (e.g. "ui/icons/star.png")
 * → ネストされたオブジェクトに変換
 */

/**
 * フラットなキーからネスト構造を構築
 * "a/b/c.png" → { a: { b: { "c.png": "rbxassetid://..." } } }
 * stripExtensions: true → { a: { b: { c: "rbxassetid://..." } } }
 */
function buildTree(lock, options = {}) {
	const { stripExtensions = false } = options;
	const tree = {};
	const keys = Object.keys(lock).sort();
	for (const key of keys) {
		const parts = key.split("/");
		let node = tree;
		for (let i = 0; i < parts.length - 1; i++) {
			if (!node[parts[i]] || typeof node[parts[i]] === "string") {
				node[parts[i]] = {};
			}
			node = node[parts[i]];
		}
		let leafKey = parts[parts.length - 1];
		if (stripExtensions) {
			leafKey = leafKey.replace(/\.[^.]+$/, "");
		}
		node[leafKey] = `rbxassetid://${lock[key].assetId}`;
	}
	return tree;
}

/**
 * .luau ファイル生成（実際のアセットID値）
 * options.strict: true → --!strict + 型注釈付き (format = "luau" 用)
 * options.stripExtensions: true → キーから拡張子を除去
 */
function generateLuau(lock, varName, options = {}) {
	const { strict = false, stripExtensions = false } = options;
	const tree = buildTree(lock, { stripExtensions });
	const body = renderLuaObject(tree, 1);

	if (strict) {
		const typeName = varName.charAt(0).toUpperCase() + varName.slice(1) + "Type";
		const typeBody = renderLuauType(tree, 1);
		return (
			`--!strict\n` +
			`-- This file is auto-generated by rocs. Do not edit manually.\n\n` +
			`type ${typeName} = ${typeBody}\n\n` +
			`local ${varName}: ${typeName} = ${body}\n\n` +
			`return ${varName}\n`
		);
	}

	return (
		`-- This file is auto-generated by rocs. Do not edit manually.\n` +
		`local ${varName} = ${body}\n\n` +
		`return ${varName}\n`
	);
}

/**
 * .d.ts ファイル生成（型定義）
 * options.stripExtensions: true → キーから拡張子を除去
 */
function generateDts(lock, varName, options = {}) {
	const { stripExtensions = false } = options;
	const tree = buildTree(lock, { stripExtensions });
	const body = renderDtsObject(tree, 1);
	return (
		`// This file is auto-generated by rocs. Do not edit manually.\n` +
		`declare const ${varName}: ${body}\n\n` +
		`export = ${varName}\n`
	);
}

/**
 * Lua テーブルリテラルとしてレンダリング
 */
function renderLuaObject(obj, depth) {
	const indent = "\t".repeat(depth);
	const closingIndent = "\t".repeat(depth - 1);
	const entries = Object.entries(obj);

	if (entries.length === 0) return "{}";

	const lines = entries.map(([key, value]) => {
		const luaKey = /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(key) ? `${key}` : `["${key}"]`;
		if (typeof value === "string") {
			return `${indent}${luaKey} = "${value}",`;
		}
		return `${indent}${luaKey} = ${renderLuaObject(value, depth + 1)},`;
	});

	return `{\n${lines.join("\n")}\n${closingIndent}}`;
}

/**
 * Luau 型定義としてレンダリング（--!strict 用）
 */
function renderLuauType(obj, depth) {
	const indent = "\t".repeat(depth);
	const closingIndent = "\t".repeat(depth - 1);
	const entries = Object.entries(obj);

	if (entries.length === 0) return "{}";

	const lines = entries.map(([key, value]) => {
		const luaKey = /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(key) ? `${key}` : `["${key}"]`;
		if (typeof value === "string") {
			return `${indent}${luaKey}: string,`;
		}
		return `${indent}${luaKey}: ${renderLuauType(value, depth + 1)},`;
	});

	return `{\n${lines.join("\n")}\n${closingIndent}}`;
}

/**
 * TypeScript 型定義オブジェクトとしてレンダリング
 */
function renderDtsObject(obj, depth) {
	const indent = "\t".repeat(depth);
	const closingIndent = "\t".repeat(depth - 1);
	const entries = Object.entries(obj);

	if (entries.length === 0) return "{}";

	const lines = entries.map(([key, value]) => {
		const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `"${key}"`;
		if (typeof value === "string") {
			return `${indent}${safeKey}: string`;
		}
		return `${indent}${safeKey}: ${renderDtsObject(value, depth + 1)}`;
	});

	return `{\n${lines.join("\n")}\n${closingIndent}}`;
}

module.exports = { generateLuau, generateDts, buildTree, renderLuaObject, renderLuauType, renderDtsObject };
