/**
 * lock オブジェクトから .luau + .d.ts ペアを生成
 * Asphalt と同じ形式: .luau に実際の値、.d.ts に型定義
 *
 * lock のキーはスラッシュ区切りの相対パス (e.g. "ui/icons/star.png")
 * → ネストされたオブジェクトに変換
 */

/**
 * フラットなキーからネスト構造を構築
 * "a/b/c.png" → { a: { b: { "c.png": "rbxassetid://..." } } }
 */
function buildTree(lock) {
	const tree = {};
	const keys = Object.keys(lock).sort();
	for (const key of keys) {
		const parts = key.split("/");
		let node = tree;
		for (let i = 0; i < parts.length - 1; i++) {
			if (!node[parts[i]] || typeof node[parts[i]] === "string") {
				node[parts[i]] = {};
			}
			node = node[parts[i]];
		}
		node[parts[parts.length - 1]] = `rbxassetid://${lock[key].assetId}`;
	}
	return tree;
}

/**
 * .luau ファイル生成（実際のアセットID値）
 */
function generateLuau(lock, varName) {
	const tree = buildTree(lock);
	const body = renderLuaObject(tree, 1);
	return (
		`-- This file is auto-generated by rocs. Do not edit manually.\n` +
		`local ${varName} = ${body}\n\n` +
		`return ${varName}\n`
	);
}

/**
 * .d.ts ファイル生成（型定義）
 */
function generateDts(lock, varName) {
	const tree = buildTree(lock);
	const body = renderDtsObject(tree, 1);
	return (
		`// This file is auto-generated by rocs. Do not edit manually.\n` +
		`declare const ${varName}: ${body}\n\n` +
		`export = ${varName}\n`
	);
}

/**
 * Lua テーブルリテラルとしてレンダリング
 */
function renderLuaObject(obj, depth) {
	const indent = "\t".repeat(depth);
	const closingIndent = "\t".repeat(depth - 1);
	const entries = Object.entries(obj);

	if (entries.length === 0) return "{}";

	const lines = entries.map(([key, value]) => {
		const luaKey = /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(key) ? `${key}` : `["${key}"]`;
		if (typeof value === "string") {
			return `${indent}${luaKey} = "${value}",`;
		}
		return `${indent}${luaKey} = ${renderLuaObject(value, depth + 1)},`;
	});

	return `{\n${lines.join("\n")}\n${closingIndent}}`;
}

/**
 * TypeScript 型定義オブジェクトとしてレンダリング
 */
function renderDtsObject(obj, depth) {
	const indent = "\t".repeat(depth);
	const closingIndent = "\t".repeat(depth - 1);
	const entries = Object.entries(obj);

	if (entries.length === 0) return "{}";

	const lines = entries.map(([key, value]) => {
		const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `"${key}"`;
		if (typeof value === "string") {
			return `${indent}${safeKey}: string`;
		}
		return `${indent}${safeKey}: ${renderDtsObject(value, depth + 1)}`;
	});

	return `{\n${lines.join("\n")}\n${closingIndent}}`;
}

module.exports = { generateLuau, generateDts, buildTree, renderLuaObject, renderDtsObject };
